### ISSUE TITLE
Source URL may be external

### ISSUE THREAD

**Issue by vorenhoutgithub** [CBG-Centrum-voor-familiegeschiedenis/PiCo#31]
https://github.com/CBG-Centrum-voor-familiegeschiedenis/PiCo/blob/main/schemas/pico_source.png
suggest that the URL to the source can (must be?) to another holder than the holding institute of the document itself. 

Is that the standard, or is this just an example? 

In the case this is allowed,  is this a 1:n relationship?

**Comment by pwoltjer** [comment]
Hi Michel, good point. The URL of a sdo:ArchiveComponent should be a link to the actual Source (if possible, not all archives have separate URL's for individual sources). The sdo:holdingArchive should be a link to the archival institution that holds/owns the record.
The link in the example did refer to the source, but on another site. It makes more sense to link to source at the Noord-Hollands archief in this example, so I changed that. 
We strongly encourage the use of permalinks, so that's overall the better link.
Thank you very much for your feedback!

**Comment by pwoltjer** [comment]
No, you are right Bob. That's why I changed it to their handle link https://hdl.handle.net/21.12102/5EC8BCCEACD6410780110CCD6B740E7C

**Comment by vorenhoutgithub** [comment]
@coret @pwoltjer Indeed, the actual current link NHA uses is via handle.net: https://hdl.handle.net/21.12102/5EC8BCCEACD6410780110CCD6B740E7C

Nice, as that compares to larger frameworks like DOI.

Maybe replace the example with Gelderlands Archief, eg https://permalink.geldersarchief.nl/00EDF85C31FD4DDB9EBCA026857BFBA1 (they also use the same software package for the website/catalogue, but chose an internal permalink) if an  informative link is preferred.
